#!/bin/bash

ACTION="Open Push"
TITLE="Push notification from `hostname`"
SUBTITLE="`date`"
ICONURL="https://dl.dropboxusercontent.com/u/172539/icons/vps.png"

if [ -e ~/.goznotify ]; then
    source ~/.goznotify
else
    echo "Config file ~/.goznotify not found."
    exit
fi    

OPTIND=1
while getopts "a:t:u:s:i:" OPTION
do
	case $OPTION in
        a)
            ACTION=$OPTARG
            ;;
        t)
            TITLE=$OPTARG
            ;;
        u)
            URL=$OPTARG
            ;;
        s)
            SUBTITLE=$OPTARG
            ;;
        i)
            ICONURL=$OPTARG
            ;;
    esac
done
shift $((OPTIND-1))

MESSAGE=${1}

# Send a notification

    /usr/bin/curl -s -d user_credentials=${APIKEY} \
        -d "notification[message]=${MESSAGE}" \
        -d "notification[long_message]=${MESSAGE}" \
        -d "notification[title]=${TITLE}" \
        -d "notification[subtitle]=${SUBTITLE}" \
        -d "notification[long_message_preview]=${MESSAGE}" \
        -d "notification[message_level]=2" \
        -d "notification[silent]=0" \
        -d "notification[icon_url]=${ICONURL}" \
        -d "notification[action_loc_key]=${ACTION}" \
        -d "notification[run_command]=${URL}" \
        https://www.appnotifications.com/account/notifications.json > /dev/null

