#!/bin/bash

ACTION="Open Push"
TITLE="Push notification from `hostname`"
SUBTITLE="`date`"
ICONURL="https://dl.dropboxusercontent.com/u/172539/icons/vps.png"
SOUND=""

if [ -e ~/.goznotify ]; then
    source ~/.goznotify
else
    echo "Config file ~/.goznotify not found."
    exit
fi    

OPTIND=1
while getopts "a:t:u:s:i:b:" OPTION
do
	case $OPTION in
        a)
            ACTION=$OPTARG
            ;;
        t)
            TITLE=$OPTARG
            ;;
        u)
            URL=$OPTARG
            ;;
        s)
            SUBTITLE=$OPTARG
            ;;
        i)
            ICONURL=$OPTARG
            ;;
        b)
            SOUND=$OPTARG
            ;;
    esac
done
shift $((OPTIND-1))

MESSAGE=${1}

# Send a notification
if [ -z "${URL}" ]
then
    curl https://api.pushbullet.com/api/pushes -u v13Kku1VLbTZM03XxmGrqu5qT4HM1k6lPZujChdG87uVM: \
       -d device_iden=ujChdG87uVMdjAiVsKnSTs \
       -d type=note \
       -d title=${TITLE} \
       -d body=${MESSAGE}
else
    curl https://api.pushbullet.com/api/pushes -u v13Kku1VLbTZM03XxmGrqu5qT4HM1k6lPZujChdG87uVM: \
        -d device_iden=ujChdG87uVMdjAiVsKnSTs \
        -d type=link \
        -d title=${TITLE} \
        -d url=${URL}
fi

exit

#    /usr/bin/curl -s -d user_credentials=${APIKEY} \
#        -d "notification[long_message]=${MESSAGE}" \
#        -d "notification[title]=${TITLE}" \
#        -d "notification[sound]=${SOUND}" \
#        ${URL} > /dev/null

#       -d "notification[message]=${MESSAGE}" \
#        -d "notification[subtitle]=${SUBTITLE}" \
#        -d "notification[long_message_preview]=${MESSAGE}" \
#        -d "notification[message_level]=2" \
#        -d "notification[silent]=0" \
#        -d "notification[icon_url]=${ICONURL}" \
#        -d "notification[action_loc_key]=${ACTION}" \
#        -d "notification[run_command]=${URL}" \

